### ISSUE TITLE
Convert to nvStereoApiI64

### ISSUE THREAD

**Issue by SNIKRS** [ekknod/nv_v2#1]
Hey i wanna convert this project to nvStereoApiI64(64bit version) for another game

i would like to know if i need to change something (in nv.rc, resource.h) to do a fake nvStereoApiI64 version ?? my main.c is ready but idk if my resource file is good to imitate nvStereoApiI64.dll

**Comment by SNIKRS** [comment]
i think im good i will to test if its good i close the thread.
![image](https://user-images.githubusercontent.com/29042883/59101985-07dc7c00-892b-11e9-9a74-25838a6684fc.png)

**Comment by ekknod** [comment]
I think this is not issue, good luck with porting it to another game.
